### PR TITLE
Added error for 'context deadline exceeded'

### PR DESCRIPTION
**Pull request by chrispassas**
If your not happy with the wording please feel free to make any adjustments.

If this isn't up the your expectations please let me know. I've been wanting to start adding more errors to this package but this is my first.

Thank you,
Chris

### CODE REVIEW

**Comment by joncalhoun** [comment]
Awesome, thanks for this! I think its safe to merge in but I'll need to run the actual hugo generate stuff since I don't have my server automatically doing that (I had issues with netlify not having a new enough hugo version)

**Comment by joncalhoun** [comment]
And it's live → https://errorsingo.com/context-context-deadline-exceeded/

**Comment by chrispassas** [comment]
@joncalhoun Thank you, I'll start work on adding some more. I've run into what I think are some less common postgresql related errors that I'd like to share.

I didn't run the hugo command to re-create the site since that results in a much larger number of files to merge. It also might cause problems depending on what versions of hugo people are using.

**Comment by joncalhoun** [comment]
Yeah what you did is completely fine - just get the markdown file there and
I'll run hugo myself before releases. Makes the PRs easier to read and
understand what they were *really* about.

**Pull request merged**
